config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'  
  end
  devise_for :users
  
  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
        resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get "search" => "searches#search"
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
    @book_comment.book_id = @book.id
    if @book_comment.save
      flash.now[:notice] = 'successfully comment posted.'
      render :book_comments
    else
      render :error
    end
  end
  def destroy
    BookComment.find(params[:id]).destroy
    @book = Book.find(params[:book_id])
    render :book_comments
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_book_comments.html.erb
<% book.book_comments.each do |book_comment| %>
  <div id="comments_error">
    <%= render 'layouts/errors', obj: book_comment %>
  </div>
  <tr>
    <td>
      <%= link_to(book_comment.user) do %>
        <%= image_tag book_comment.user.get_profile_image, size: "100x100" %><br>
        <%= book_comment.user.name %>
      <% end %>
    </td>
    <td class="p-2"><%= book_comment.comment %></td>
    <% if book_comment.user == current_user %>
      <td><%= link_to 'Destroy', book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: "btn btn-danger btn-sm" %></td>
    <% end %>
  </tr>
<% end %>

app/views/book_comments/_comment_form.html.erb
<%= form_with model: [book, book_comment], local: false do |f| %>

  <%= f.text_area :comment, rows: '5', class: "form-control mb-1" %>
  <%= f.submit '送信' %>
<% end %>

app/views/book_comments/book_comments.js.erb
$('#book_comments').html("<%= j(render 'book_comments', book: @book) %>");
$('textarea').val('');
$('#comments_error').empty();

app/views/book_comments/error.js.erb
$('#comments_error').html("<%= j(render 'layouts/errors', obj: @book_comment) %>");